### PR TITLE
Fix reference to non-existent setting from config.yaml

### PR DESCRIPTION
**Pull request by kitar7**
I've just changed one line. Now as in config.yaml 'ill_branch' instead of 'ill_library'

### CODE REVIEW

**Comment by kitar7** [comment]
Sorry I closed this accidentally.

**Review by taskula — CHANGES_REQUESTED** [review]
Code change looks good to me.

But the commit title and description (as well as the pull request title and description) should be more descriptive to the change especially explaining why you are making this change. Currently, just based on the commit title and description, we get no idea why you've made this change. See https://wiki.koha-community.org/wiki/Commit_messages

Please rewrite the commit title and description.

**Comment by taskula** [comment]
Additionally, note that you can add references to other commits or pull requests in your commit message. It can be useful, especially in this pull request because your change is related to other commits in this repository.

**Review by taskula — APPROVED** [review]
Changes approved.

@MagnusEnger should we use the master branch of fjarrlan2 for pushing our pull requests?

**Comment by MagnusEnger** [comment]
My thought was to use the fjarrlan2 branch for all our development now, and then merge that into master when the project is done. I'm a bit worried about people updating and getting new features that are not really ready yet, if we develop on the master branch. But I'm open to arguments if you  think master is better. :-)

**Pull request merged**
